version: "3.8"
services:
  jenkins:
    container_name: jenkins
    image: jenkins
    ports: 
      - "8082:8080"
      - "50000:50000"
    volumes:
      - ./var/jenkins_home:/var/jenkins_home
#  docker run -p 8080:8080 -p 50000:50000 -v /your/home:/var/jenkins_home jenkins